#   Copyright (C) 2025 John Törnblom
#
# This file is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; see the file COPYING. If not see
# <http://www.gnu.org/licenses/>.

PS4_HOST ?= ps4
PS4_PORT ?= 9021

ifdef PS4_PAYLOAD_SDK
    include $(PS4_PAYLOAD_SDK)/toolchain/orbis.mk
else
    $(error PS4_PAYLOAD_SDK is undefined)
endif

BIN   := gdbsrv-ps4.elf
SRCS := src/gdb_serve.c src/gdb_resp.c src/gdb_sig.c src/gdb_pkt.c
SRCS += src/ps4/main.c src/ps4/gdb_arch.c src/ps4/pt.c src/ps4/elfldr.c

CFLAGS := -Isrc -Wall #-DGDB_PKT_TRACE

all: $(BIN)

clean:
	rm -rf $(BIN)

$(BIN): $(SRCS)
	$(CC) $(CFLAGS) -o $@ $^

test: $(BIN)
	$(PS4_DEPLOY) -h $(PS4_HOST) -p $(PS4_PORT) $^
