#   Copyright (C) 2024 John Törnblom
#
# This file is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; see the file COPYING. If not see
# <http://www.gnu.org/licenses/>.

LINUX_HOST ?= localhost

BIN  := payload-linux.elf
SRCS := payload.c

CFLAGS := -Wall -Werror -g
LDADD :=

all: $(BIN)

clean:
	rm -rf $(BIN)

$(BIN): $(SRCS)
	$(CC) $(CFLAGS) $(LDADD) -o $@ $^

test: $(BIN)
	gdb \
	-ex "target extended-remote $(LINUX_HOST):2159" \
	-ex "file $(BIN)" \
	-ex "remote put $(BIN) /tmp/$(BIN)" \
	-ex "set remote exec-file /tmp/$(BIN)" \
	-ex "start"
